# Generated by Django 5.2.10 on 2026-01-25 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('questionbank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(db_index=True)),
                ('max_score', models.IntegerField(default=100, help_text='Maximum possible score for this homework')),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Whether this homework is visible to students')),
                ('assigned_by', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_homework', to=settings.AUTH_USER_MODEL)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_assignments', to='classes.class')),
                ('questions', models.ManyToManyField(blank=True, related_name='homework_assignments', to='questionbank.question')),
            ],
            options={
                'db_table': 'homework',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, help_text='When the student submitted the homework', null=True)),
                ('is_late', models.BooleanField(db_index=True, default=False, help_text='Whether the submission was late')),
                ('score', models.IntegerField(blank=True, help_text='Score achieved (auto-calculated)', null=True)),
                ('answers', models.JSONField(default=dict, help_text='Student answers: {question_id: selected_answer}')),
                ('time_spent_seconds', models.IntegerField(default=0, help_text='Total time spent on homework in seconds')),
                ('feedback', models.TextField(blank=True, help_text='Teacher feedback on the submission')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.homework')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'homework_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['class_obj'], name='homework_class_o_9c664d_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['assigned_by'], name='homework_assigne_a8eda4_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['due_date'], name='homework_due_dat_1a4fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['is_published'], name='homework_is_publ_e40d06_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['class_obj', 'due_date'], name='homework_class_o_e1b450_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['homework', 'student'], name='homework_su_homewor_583d50_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['student', 'submitted_at'], name='homework_su_student_19c4fd_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['homework', 'submitted_at'], name='homework_su_homewor_d0a5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['is_late'], name='homework_su_is_late_6ecbbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='homeworksubmission',
            unique_together={('homework', 'student')},
        ),
    ]
