# Generated by Django 5.2.10 on 2026-02-18 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_announcement_classresource_class_schedule_config_and_more'),
        ('homework', '0001_initial'),
        ('questionbank', '0002_question_questions_created_2d11fa_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='topic',
            field=models.CharField(blank=True, db_index=True, help_text='Specific topic or subcategory this homework addresses (for analytics tracking)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='submission_file',
            field=models.FileField(blank=True, help_text='Optional file submission (document, image, etc.)', null=True, upload_to='homework_submissions/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='assigned_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['ADMIN', 'MAIN_TEACHER']}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_homework', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['created_at'], name='homework_created_368c48_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['created_at'], name='homework_su_created_e35da0_idx'),
        ),
    ]
