# Generated by Django 5.2.10 on 2026-01-25 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('question_type', models.CharField(choices=[('MATH', 'Math'), ('READING', 'Reading'), ('WRITING', 'Writing')], db_index=True, help_text='SAT section: Math, Reading, or Writing', max_length=10)),
                ('skill_tag', models.CharField(db_index=True, help_text="Specific skill area (e.g., 'Algebra', 'Grammar', 'Main Idea')", max_length=100)),
                ('difficulty', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], db_index=True, help_text='Difficulty level from 1 (easiest) to 5 (hardest)')),
                ('question_text', models.TextField(help_text='The full question text')),
                ('question_image', models.ImageField(blank=True, help_text='Optional image for the question', null=True, upload_to='question_images/')),
                ('options', models.JSONField(help_text="Multiple choice options: {A: '...', B: '...', C: '...', D: '...'}")),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Correct answer choice', max_length=1)),
                ('explanation', models.TextField(help_text='Explanation of the correct answer')),
                ('estimated_time_seconds', models.IntegerField(default=60, help_text='Estimated time to solve in seconds')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this question is available for use')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['question_type'], name='questions_questio_8af709_idx'), models.Index(fields=['skill_tag'], name='questions_skill_t_82087e_idx'), models.Index(fields=['difficulty'], name='questions_difficu_8150ad_idx'), models.Index(fields=['is_active'], name='questions_is_acti_ba6b3c_idx'), models.Index(fields=['question_type', 'difficulty'], name='questions_questio_923598_idx'), models.Index(fields=['question_type', 'skill_tag'], name='questions_questio_5468de_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('selected_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Answer selected by the student', max_length=1)),
                ('is_correct', models.BooleanField(db_index=True, help_text='Whether the answer was correct')),
                ('time_spent_seconds', models.IntegerField(help_text='Time spent on this question in seconds')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the question was attempted')),
                ('context', models.CharField(choices=[('HOMEWORK', 'Homework'), ('MOCK_EXAM', 'Mock Exam'), ('PRACTICE', 'Independent Practice')], db_index=True, default='PRACTICE', help_text='Context in which the question was attempted', max_length=20)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='questionbank.question')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_attempts',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['student', 'question', 'attempted_at'], name='question_at_student_53f916_idx'), models.Index(fields=['student', 'attempted_at'], name='question_at_student_974db6_idx'), models.Index(fields=['question', 'is_correct'], name='question_at_questio_612cb5_idx'), models.Index(fields=['student', 'is_correct'], name='question_at_student_f98edf_idx'), models.Index(fields=['context'], name='question_at_context_d091e6_idx')],
                'unique_together': {('question', 'student', 'attempted_at')},
            },
        ),
    ]
