# Generated by Django 5.2.10 on 2026-02-18 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='questions_created_2d11fa_idx'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['created_at'], name='question_at_created_9c0772_idx'),
        ),
    ]
