# Generated by Django 5.2.10 on 2026-02-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0002_question_questions_created_2d11fa_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_math_input',
            field=models.BooleanField(default=False, help_text='Whether this is a math input (grid-in) question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(help_text='Correct answer choice (A/B/C/D or text for math input)', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, help_text="Multiple choice options: {A: '...', B: '...', C: '...', D: '...'}", null=True),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='selected_answer',
            field=models.CharField(help_text='Answer selected by the student', max_length=50),
        ),
    ]
