# Generated by Django 5.2.10 on 2026-01-25 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('period_type', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('ALL_TIME', 'All Time')], db_index=True, help_text='Type of ranking period', max_length=10)),
                ('period_start', models.DateTimeField(db_index=True, help_text='Start date of the ranking period')),
                ('period_end', models.DateTimeField(db_index=True, help_text='End date of the ranking period')),
                ('total_points', models.IntegerField(db_index=True, default=0, help_text='Total points earned in the period')),
                ('homework_completion_rate', models.FloatField(default=0.0, help_text='Percentage of homework completed (0-100)')),
                ('homework_accuracy', models.FloatField(default=0.0, help_text='Average homework accuracy (0-100)')),
                ('mock_exam_scores', models.JSONField(default=list, help_text='List of mock exam scores in the period')),
                ('rank', models.IntegerField(db_index=True, help_text='Rank position in the leaderboard')),
                ('previous_rank', models.IntegerField(blank=True, help_text='Previous rank for comparison', null=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rankings',
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['period_type', 'period_start', 'rank'], name='rankings_period__ef189c_idx'), models.Index(fields=['student', 'period_type', 'period_start'], name='rankings_student_0fb8ea_idx'), models.Index(fields=['period_type', 'period_start'], name='rankings_period__e15739_idx'), models.Index(fields=['rank'], name='rankings_rank_01ee0c_idx'), models.Index(fields=['total_points'], name='rankings_total_p_c306d4_idx')],
                'unique_together': {('student', 'period_type', 'period_start')},
            },
        ),
    ]
