# Generated by Django 5.2.10 on 2026-02-18 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ranking',
            index=models.Index(fields=['created_at'], name='rankings_created_56ebf6_idx'),
        ),
    ]
