# Generated by Django 5.2.10 on 2026-01-25 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('max_students', models.IntegerField(default=50, help_text='Maximum number of students')),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='enrolled_classes', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher'], name='classes_teacher_3b552b_idx'), models.Index(fields=['is_active'], name='classes_is_acti_7c0b49_idx'), models.Index(fields=['start_date'], name='classes_start_d_041972_idx'), models.Index(fields=['end_date'], name='classes_end_dat_4cd9d4_idx'), models.Index(fields=['teacher', 'is_active'], name='classes_teacher_095d85_idx')],
            },
        ),
    ]
