# Generated by Django 5.2.10 on 2026-02-18 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'class_announcements',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('PDF', 'PDF Document'), ('LINK', 'External Link'), ('VIDEO', 'Video'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='class_resources/')),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'class_resources',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='class',
            name='schedule_config',
            field=models.JSONField(blank=True, default=dict, help_text="Schedule configuration e.g. {'days': ['MON', 'WED'], 'time': '10:00'}"),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role__in': ['MAIN_TEACHER', 'SUPPORT_TEACHER']}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['created_at'], name='classes_created_451968_idx'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='classes.class'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classresource',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='classes.class'),
        ),
        migrations.AddField(
            model_name='classresource',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['created_at'], name='class_annou_created_2041c6_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['class_obj', 'is_active'], name='class_annou_class_o_dd7ee3_idx'),
        ),
        migrations.AddIndex(
            model_name='classresource',
            index=models.Index(fields=['created_at'], name='class_resou_created_256899_idx'),
        ),
    ]
