# Generated by Django 5.2.10 on 2026-02-08 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='classes.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'class_announcements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['class_obj', 'is_active'], name='class_annou_class_o_dd7ee3_idx'), models.Index(fields=['created_at'], name='class_annou_created_2041c6_idx')],
            },
        ),
    ]
