# Generated by Django 5.2.10 on 2026-01-25 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('word', models.CharField(db_index=True, help_text='Vocabulary word', max_length=100)),
                ('definition', models.TextField(help_text='Definition of the word')),
                ('example_sentence', models.TextField(blank=True, help_text='Example sentence using the word')),
                ('difficulty', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], db_index=True, default=3, help_text='Difficulty level from 1 (easiest) to 5 (hardest)')),
                ('part_of_speech', models.CharField(choices=[('NOUN', 'Noun'), ('VERB', 'Verb'), ('ADJECTIVE', 'Adjective'), ('ADVERB', 'Adverb'), ('OTHER', 'Other')], db_index=True, default='OTHER', help_text='Part of speech', max_length=20)),
                ('synonyms', models.TextField(blank=True, help_text='Comma-separated list of synonyms')),
                ('antonyms', models.TextField(blank=True, help_text='Comma-separated list of antonyms')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this flashcard is available for review')),
            ],
            options={
                'db_table': 'flashcards',
                'ordering': ['word'],
                'indexes': [models.Index(fields=['word'], name='flashcards_word_83b269_idx'), models.Index(fields=['difficulty'], name='flashcards_difficu_da7cdb_idx'), models.Index(fields=['part_of_speech'], name='flashcards_part_of_0bda84_idx'), models.Index(fields=['is_active'], name='flashcards_is_acti_c14122_idx'), models.Index(fields=['difficulty', 'is_active'], name='flashcards_difficu_c34bec_idx')],
            },
        ),
        migrations.CreateModel(
            name='FlashcardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_reviewed', models.DateTimeField(blank=True, db_index=True, help_text='When this flashcard was last reviewed', null=True)),
                ('next_review', models.DateTimeField(blank=True, db_index=True, help_text='When this flashcard should be reviewed next', null=True)),
                ('review_count', models.IntegerField(default=0, help_text='Number of times this flashcard has been reviewed')),
                ('ease_factor', models.FloatField(default=2.5, help_text='Ease factor for spaced repetition (SM-2 algorithm)')),
                ('interval_days', models.IntegerField(default=1, help_text='Days until next review')),
                ('is_mastered', models.BooleanField(db_index=True, default=False, help_text='Whether this flashcard is considered mastered')),
                ('consecutive_correct', models.IntegerField(default=0, help_text='Number of consecutive correct reviews')),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='flashcards.flashcard')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flashcard_progress',
                'ordering': ['next_review'],
                'indexes': [models.Index(fields=['student', 'next_review'], name='flashcard_p_student_2e0149_idx'), models.Index(fields=['student', 'is_mastered'], name='flashcard_p_student_83b611_idx'), models.Index(fields=['student', 'last_reviewed'], name='flashcard_p_student_bcb82d_idx'), models.Index(fields=['flashcard', 'student'], name='flashcard_p_flashca_028493_idx'), models.Index(fields=['next_review'], name='flashcard_p_next_re_695320_idx')],
                'unique_together': {('flashcard', 'student')},
            },
        ),
    ]
