# Generated by Django 5.2.10 on 2026-02-18 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['created_at'], name='flashcards_created_1788b3_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcardprogress',
            index=models.Index(fields=['created_at'], name='flashcard_p_created_e71737_idx'),
        ),
    ]
