# Generated by Django 5.2.10 on 2026-01-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography or description', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='grade_level',
            field=models.CharField(blank=True, help_text='Grade level (e.g., 9th, 10th, 11th, 12th)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active_date',
            field=models.DateField(blank=True, db_index=True, help_text='Last date the user was active (for streak calculation)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='streak_count',
            field=models.PositiveIntegerField(default=0, help_text='Current streak of consecutive days active'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_active_date'], name='users_last_ac_c1ee67_idx'),
        ),
    ]
