# Generated by Django 5.2.10 on 2026-02-18 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_main_teacher',
            field=models.ForeignKey(blank=True, help_text='Main teacher for this support teacher', limit_choices_to={'role': 'MAIN_TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography or description', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='grade_level',
            field=models.CharField(blank=True, help_text='Grade level (e.g., 9th, 10th, 11th, 12th)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_frozen',
            field=models.BooleanField(default=False, help_text='Manually freeze/unfreeze account'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active_date',
            field=models.DateField(blank=True, db_index=True, help_text='Last date the user was active (for streak calculation)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='streak_count',
            field=models.PositiveIntegerField(default=0, help_text='Current streak of consecutive days active'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateField(blank=True, db_index=True, help_text="Date when student's subscription expires", null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MAIN_TEACHER', 'Main Teacher'), ('SUPPORT_TEACHER', 'Support Teacher'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MAIN_TEACHER', 'Main Teacher'), ('SUPPORT_TEACHER', 'Support Teacher'), ('STUDENT', 'Student')], db_index=True, default='STUDENT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_active_date'], name='users_last_ac_c1ee67_idx'),
        ),
    ]
