# Generated by Django 5.2.10 on 2026-01-25 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionbank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('exam_type', models.CharField(choices=[('FULL', 'Full SAT'), ('MATH_ONLY', 'Math Only'), ('READING_WRITING_ONLY', 'Reading & Writing Only')], db_index=True, default='FULL', max_length=20)),
                ('math_time_limit', models.IntegerField(default=2700, help_text='Math section time limit in seconds')),
                ('reading_time_limit', models.IntegerField(default=2400, help_text='Reading section time limit in seconds')),
                ('writing_time_limit', models.IntegerField(default=2400, help_text='Writing section time limit in seconds')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this exam is available for students')),
                ('math_questions', models.ManyToManyField(blank=True, limit_choices_to={'question_type': 'MATH'}, related_name='math_exams', to='questionbank.question')),
                ('reading_questions', models.ManyToManyField(blank=True, limit_choices_to={'question_type': 'READING'}, related_name='reading_exams', to='questionbank.question')),
                ('writing_questions', models.ManyToManyField(blank=True, limit_choices_to={'question_type': 'WRITING'}, related_name='writing_exams', to='questionbank.question')),
            ],
            options={
                'db_table': 'mock_exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the student started the exam')),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, help_text='When the student submitted the exam', null=True)),
                ('math_raw_score', models.IntegerField(blank=True, help_text='Raw score for math section (0-58)', null=True)),
                ('reading_raw_score', models.IntegerField(blank=True, help_text='Raw score for reading section (0-52)', null=True)),
                ('writing_raw_score', models.IntegerField(blank=True, help_text='Raw score for writing section (0-44)', null=True)),
                ('total_raw_score', models.IntegerField(blank=True, help_text='Total raw score', null=True)),
                ('math_scaled_score', models.IntegerField(blank=True, help_text='Scaled score for math section (200-800)', null=True)),
                ('reading_scaled_score', models.IntegerField(blank=True, help_text='Scaled score for reading section (200-800)', null=True)),
                ('writing_scaled_score', models.IntegerField(blank=True, help_text='Scaled score for writing section (200-800)', null=True)),
                ('sat_score', models.IntegerField(blank=True, db_index=True, help_text='Final SAT score (400-1600)', null=True)),
                ('answers', models.JSONField(default=dict, help_text='Student answers: {section: {question_id: answer}}')),
                ('time_spent_by_section', models.JSONField(default=dict, help_text='Time spent by section: {math: int, reading: int, writing: int}')),
                ('is_completed', models.BooleanField(db_index=True, default=False, help_text='Whether the exam attempt is completed')),
                ('mock_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mockexams.mockexam')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='mock_exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mock_exam_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mockexam',
            index=models.Index(fields=['exam_type'], name='mock_exams_exam_ty_7b7645_idx'),
        ),
        migrations.AddIndex(
            model_name='mockexam',
            index=models.Index(fields=['is_active'], name='mock_exams_is_acti_061ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='mockexam',
            index=models.Index(fields=['created_at'], name='mock_exams_created_bded63_idx'),
        ),
        migrations.AddIndex(
            model_name='mockexamattempt',
            index=models.Index(fields=['student', 'submitted_at'], name='mock_exam_a_student_134f40_idx'),
        ),
        migrations.AddIndex(
            model_name='mockexamattempt',
            index=models.Index(fields=['mock_exam', 'submitted_at'], name='mock_exam_a_mock_ex_8a195e_idx'),
        ),
        migrations.AddIndex(
            model_name='mockexamattempt',
            index=models.Index(fields=['sat_score'], name='mock_exam_a_sat_sco_d9f6ac_idx'),
        ),
        migrations.AddIndex(
            model_name='mockexamattempt',
            index=models.Index(fields=['is_completed'], name='mock_exam_a_is_comp_fe590e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mockexamattempt',
            unique_together={('mock_exam', 'student')},
        ),
    ]
