# Generated by Django 5.2.10 on 2026-02-18 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockexams', '0001_initial'),
        ('questionbank', '0002_question_questions_created_2d11fa_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BluebookExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('total_duration_minutes', models.IntegerField(default=134, help_text='Total test duration in minutes (fixed at 134 for Digital SAT)')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BluebookExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('current_module_start_time', models.DateTimeField(blank=True, null=True)),
                ('reading_writing_difficulty', models.CharField(choices=[('BASELINE', 'Baseline'), ('EASIER', 'Easier'), ('HARDER', 'Harder')], default='BASELINE', max_length=10)),
                ('math_difficulty', models.CharField(choices=[('BASELINE', 'Baseline'), ('EASIER', 'Easier'), ('HARDER', 'Harder')], default='BASELINE', max_length=10)),
                ('module_answers', models.JSONField(blank=True, default=dict, help_text='Answers stored by module ID')),
                ('module_time_spent', models.JSONField(blank=True, default=dict, help_text='Time spent on each module in seconds')),
                ('flagged_questions', models.JSONField(blank=True, default=dict, help_text='Flagged questions by module ID')),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('is_paused', models.BooleanField(default=False)),
                ('reading_writing_score', models.IntegerField(blank=True, null=True)),
                ('math_score', models.IntegerField(blank=True, null=True)),
                ('total_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BluebookModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('module_order', models.IntegerField(choices=[(1, 'Module 1 (Baseline)'), (2, 'Module 2 (Adaptive)')], help_text='Module order within section (1 or 2)')),
                ('time_limit_minutes', models.IntegerField(help_text='Time limit for this module in minutes')),
                ('difficulty_level', models.CharField(choices=[('BASELINE', 'Baseline'), ('EASIER', 'Easier'), ('HARDER', 'Harder')], default='BASELINE', help_text='Difficulty level for adaptive modules', max_length=10)),
            ],
            options={
                'ordering': ['section__section_order', 'module_order'],
            },
        ),
        migrations.CreateModel(
            name='BluebookQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('selected_answer', models.CharField(max_length=10)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('is_flagged', models.BooleanField(default=False)),
                ('answer_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['module', 'answer_order'],
            },
        ),
        migrations.CreateModel(
            name='BluebookSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('section_type', models.CharField(choices=[('READING_WRITING', 'Reading & Writing'), ('MATH', 'Math')], db_index=True, max_length=20)),
                ('section_order', models.IntegerField(help_text='Order of section (1 or 2)')),
                ('total_duration_minutes', models.IntegerField(help_text='Total duration for both modules in this section')),
            ],
            options={
                'ordering': ['section_order'],
            },
        ),
        migrations.AddIndex(
            model_name='mockexamattempt',
            index=models.Index(fields=['created_at'], name='mock_exam_a_created_1efec4_idx'),
        ),
        migrations.AddField(
            model_name='bluebookexamattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mockexams.bluebookexam'),
        ),
        migrations.AddField(
            model_name='bluebookexamattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bluebook_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bluebookmodule',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='bluebook_modules', to='questionbank.question'),
        ),
        migrations.AddField(
            model_name='bluebookexamattempt',
            name='completed_modules',
            field=models.ManyToManyField(blank=True, related_name='completed_attempts', to='mockexams.bluebookmodule'),
        ),
        migrations.AddField(
            model_name='bluebookexamattempt',
            name='current_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_attempts', to='mockexams.bluebookmodule'),
        ),
        migrations.AddField(
            model_name='bluebookquestionresponse',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mockexams.bluebookexamattempt'),
        ),
        migrations.AddField(
            model_name='bluebookquestionresponse',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mockexams.bluebookmodule'),
        ),
        migrations.AddField(
            model_name='bluebookquestionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bluebook_responses', to='questionbank.question'),
        ),
        migrations.AddField(
            model_name='bluebooksection',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='mockexams.bluebookexam'),
        ),
        migrations.AddField(
            model_name='bluebookmodule',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='mockexams.bluebooksection'),
        ),
        migrations.AddField(
            model_name='bluebookexamattempt',
            name='current_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_attempts', to='mockexams.bluebooksection'),
        ),
        migrations.AlterUniqueTogether(
            name='bluebookquestionresponse',
            unique_together={('attempt', 'module', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='bluebooksection',
            unique_together={('exam', 'section_order')},
        ),
        migrations.AlterUniqueTogether(
            name='bluebookmodule',
            unique_together={('section', 'module_order')},
        ),
        migrations.AlterUniqueTogether(
            name='bluebookexamattempt',
            unique_together={('exam', 'student')},
        ),
    ]
