# Generated by Django 5.2.10 on 2026-02-07 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockexams', '0001_initial'),
        ('questionbank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BluebookExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('total_duration_minutes', models.IntegerField(default=134, help_text='Total test duration in minutes (fixed at 134 for Digital SAT)')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BluebookSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('section_type', models.CharField(choices=[('READING_WRITING', 'Reading & Writing'), ('MATH', 'Math')], db_index=True, max_length=20)),
                ('section_order', models.IntegerField(help_text='Order of section (1 or 2)')),
                ('total_duration_minutes', models.IntegerField(help_text='Total duration for both modules in this section')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='mockexams.bluebookexam')),
            ],
            options={
                'ordering': ['section_order'],
                'unique_together': {('exam', 'section_order')},
            },
        ),
        migrations.CreateModel(
            name='BluebookModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('module_order', models.IntegerField(choices=[(1, 'Module 1 (Baseline)'), (2, 'Module 2 (Adaptive)')], help_text='Module order within section (1 or 2)')),
                ('time_limit_minutes', models.IntegerField(help_text='Time limit for this module in minutes')),
                ('difficulty_level', models.CharField(choices=[('BASELINE', 'Baseline'), ('EASIER', 'Easier'), ('HARDER', 'Harder')], default='BASELINE', help_text='Difficulty level for adaptive modules', max_length=10)),
                ('questions', models.ManyToManyField(blank=True, related_name='bluebook_modules', to='questionbank.question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='mockexams.bluebooksection')),
            ],
            options={
                'ordering': ['section__section_order', 'module_order'],
                'unique_together': {('section', 'module_order')},
            },
        ),
        migrations.CreateModel(
            name='BluebookExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('current_module_start_time', models.DateTimeField(blank=True, null=True)),
                ('reading_writing_difficulty', models.CharField(choices=[('BASELINE', 'Baseline'), ('EASIER', 'Easier'), ('HARDER', 'Harder')], default='BASELINE', max_length=10)),
                ('math_difficulty', models.CharField(choices=[('BASELINE', 'Baseline'), ('EASIER', 'Easier'), ('HARDER', 'Harder')], default='BASELINE', max_length=10)),
                ('module_answers', models.JSONField(blank=True, default=dict, help_text='Answers stored by module ID')),
                ('module_time_spent', models.JSONField(blank=True, default=dict, help_text='Time spent on each module in seconds')),
                ('flagged_questions', models.JSONField(blank=True, default=dict, help_text='Flagged questions by module ID')),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('is_paused', models.BooleanField(default=False)),
                ('reading_writing_score', models.IntegerField(blank=True, null=True)),
                ('math_score', models.IntegerField(blank=True, null=True)),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mockexams.bluebookexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bluebook_attempts', to=settings.AUTH_USER_MODEL)),
                ('completed_modules', models.ManyToManyField(blank=True, related_name='completed_attempts', to='mockexams.bluebookmodule')),
                ('current_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_attempts', to='mockexams.bluebookmodule')),
                ('current_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_attempts', to='mockexams.bluebooksection')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='BluebookQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('selected_answer', models.CharField(max_length=10)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('is_flagged', models.BooleanField(default=False)),
                ('answer_order', models.IntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mockexams.bluebookexamattempt')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mockexams.bluebookmodule')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bluebook_responses', to='questionbank.question')),
            ],
            options={
                'ordering': ['module', 'answer_order'],
                'unique_together': {('attempt', 'module', 'question')},
            },
        ),
    ]
