# Generated by Django 5.2.10 on 2026-02-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockexams', '0002_bluebookexam_bluebookexamattempt_bluebookmodule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluebookquestionresponse',
            name='selected_answer',
            field=models.CharField(max_length=50),
        ),
    ]
