# Generated by Django 5.2.10 on 2026-01-25 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('date', models.DateField(db_index=True, help_text='Date of progress record')),
                ('homework_completed', models.IntegerField(default=0, help_text='Number of homework assignments completed')),
                ('homework_total', models.IntegerField(default=0, help_text='Total number of homework assignments')),
                ('homework_accuracy', models.FloatField(default=0.0, help_text='Average homework accuracy (0-100)')),
                ('mock_exams_taken', models.IntegerField(default=0, help_text='Number of mock exams taken')),
                ('latest_sat_score', models.IntegerField(blank=True, help_text='Latest SAT score', null=True)),
                ('average_sat_score', models.FloatField(blank=True, help_text='Average SAT score', null=True)),
                ('flashcards_mastered', models.IntegerField(default=0, help_text='Number of flashcards mastered')),
                ('flashcards_total', models.IntegerField(default=0, help_text='Total number of flashcards')),
                ('study_time_minutes', models.IntegerField(default=0, help_text='Total study time in minutes for the day')),
                ('streak_days', models.IntegerField(default=0, help_text='Current study streak in days')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_progress',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['student', 'date'], name='student_pro_student_21b668_idx'), models.Index(fields=['date'], name='student_pro_date_74c413_idx'), models.Index(fields=['student', 'streak_days'], name='student_pro_student_a084c8_idx')],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('session_type', models.CharField(choices=[('HOMEWORK', 'Homework'), ('MOCK_EXAM', 'Mock Exam'), ('FLASHCARDS', 'Flashcards'), ('QUESTION_PRACTICE', 'Question Practice'), ('REVIEW', 'Review')], db_index=True, max_length=20)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0, help_text='Session duration in minutes')),
                ('questions_attempted', models.IntegerField(default=0, help_text='Number of questions attempted')),
                ('questions_correct', models.IntegerField(default=0, help_text='Number of questions answered correctly')),
                ('flashcards_reviewed', models.IntegerField(default=0, help_text='Number of flashcards reviewed')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['student', 'started_at'], name='study_sessi_student_1f6942_idx'), models.Index(fields=['session_type', 'started_at'], name='study_sessi_session_3a3130_idx'), models.Index(fields=['started_at'], name='study_sessi_started_9a9b30_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeakArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('area_type', models.CharField(choices=[('MATH', 'Math'), ('READING', 'Reading'), ('WRITING', 'Writing'), ('VOCABULARY', 'Vocabulary')], db_index=True, max_length=20)),
                ('subcategory', models.CharField(blank=True, help_text='Specific subcategory within the area', max_length=50)),
                ('weakness_score', models.FloatField(default=0.0, help_text='Weakness score (0-100, higher = weaker)')),
                ('question_count', models.IntegerField(default=0, help_text='Number of questions analyzed')),
                ('correct_count', models.IntegerField(default=0, help_text='Number of correct answers')),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='weak_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weak_areas',
                'ordering': ['-weakness_score'],
                'indexes': [models.Index(fields=['student', 'area_type'], name='weak_areas_student_9576b9_idx'), models.Index(fields=['student', 'weakness_score'], name='weak_areas_student_183c54_idx'), models.Index(fields=['area_type', 'weakness_score'], name='weak_areas_area_ty_8d814f_idx')],
                'unique_together': {('student', 'area_type', 'subcategory')},
            },
        ),
    ]
