# Generated by Django 5.2.10 on 2026-02-18 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['created_at'], name='student_pro_created_4af49d_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['created_at'], name='study_sessi_created_565700_idx'),
        ),
        migrations.AddIndex(
            model_name='weakarea',
            index=models.Index(fields=['created_at'], name='weak_areas_created_4a8388_idx'),
        ),
    ]
